name: Deploy Frontend to S3

on:
  push:
    branches:
      - aws_deploy

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: |
          export VUE_APP_API_URL="https://portal.thmarinegold.com"
          npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          # aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          # aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-access-key-id: "AKIAYYT2EEIAQT4AK5QH"
          aws-secret-access-key: "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"
          aws-region: ap-southeast-1

      - name: Deploy to S3
        run: |
          if [ ! -d "./dist" ]; then
            echo "Error: ./dist folder does not exist."
            exit 1
          fi
          aws s3 sync ./dist s3://mrg-s3fe-prod-aps11-thegift-backoffice/thegift_backoffice/ --delete
