name: Deploy Frontend to S3

on:
  pull_request:
    branches:
      - main
    paths:
      - 'frontend/**'
    types: [closed]  

jobs:
  deploy-frontend:
    if: github.event.pull_request.merged == true  
    runs-on: ubuntu-latest


    permissions:
      id-token: write 
      contents: read
    
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: |
          export VUE_APP_API_URL="https://portal.thmarinegold.com"
          npm run build

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::602625286657:role/mrg-oidc-github-action
          aws-region: ap-southeast-1

      - name: Deploy to S3
        run: |
          if [ ! -d "./dist" ]; then
            echo "Error: ./dist folder does not exist."
            exit 1
          fi
          aws s3 sync ./dist s3://mrg-s3fe-prod-aps11-thegift-backoffice/thegift_backoffice/ --delete