name: Deploy Frontend

on:
  pull_request:
    branches:
      - main
    paths:
      - 'frontend/**'
    types: [closed]  

jobs:
  build:
    if: github.event.pull_request.merged == true  
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: |
          export VUE_APP_API_URL="https://portal.thmarinegold.com"
          npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: frontend/dist/**

  deploy:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      id-token: write 
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-build
          path: dist

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::602625286657:role/mrg-oidc-github-action
          aws-region: ap-southeast-1

      - name: Deploy to S3
        env:
          AWS_REGION: ap-southeast-1
        run: |
          aws s3 sync ./dist s3://mrg-s3fe-prod-aps11-thegift-backoffice/thegift_backoffice/ --delete
